name: StatCollector
version: '${project.version}'
main: me.cooleg.statcollector.StatCollector
api-version: '1.18'
softdepend:
  - CommandAPI
commands:
  savestats:
    permission: statistics.save
  togglecollecting:
    permission: statistics.toggle
  wipestats:
    permission: statistics.wipe
libraries:
  - club.minnced:discord-webhooks:0.8.4